name: Build - react

on:  
  push:
    branches:
      - "main"
    #paths: 
    #  - 'package.json'

jobs:
  react_android:
    runs-on: macos-latest
        
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
         node-version: 16.x
         registry-url: https://registry.npmjs.org/
         
      - name: Prepare NDK dir for caching
        run: |
          sudo mkdir -p /usr/local/lib/android/sdk/ndk
          sudo chmod -R 777 /usr/local/lib/android/sdk/ndk
          sudo chown -R $USER:$USER /usr/local/lib/android/sdk/ndk
          
      - name: NDK Cache
        id: ndk-cache
        uses: actions/cache@v2
        with:
          path: /usr/local/lib/android/sdk/ndk
          key: ndk-cache-21.0.6113669-v2
          
      - name: Install NDK
        if: steps.ndk-cache.outputs.cache-hit != 'true'
        run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;21.0.6113669"
      
       
      # - name: Corrected Package name
      #  run: |
      #    sed  -i.bak 's/@woosmap\/react-native-plugin-geofencing/react-native-plugin-geofencing/g' package.json
      #    rm package.json.bak
         
      - name: Build it 
        run: |
          yarn
          cd example
          yarn
                  
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: yarn example run android
          

          
