name: Publish Geofence SDK - react

on:  
  push:
    branches:
      - "main"
    # paths: 
    #  - 'package.json'

jobs:
  react_ios:
    runs-on: macos-latest
        
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
         node-version: 16.x
         registry-url: https://registry.npmjs.org/
         
         
      - name: Capture release version 
        id: vars
        run: echo ::set-output name=tag::$(node -p "require('./package.json').version")
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}  
        
      # - name: Corrected Package name
      #  run: |
      #    sed  -i.bak 's/@woosmap\/react-native-plugin-geofencing/react-native-plugin-geofencing/g' package.json
      #    rm package.json.bak
         
      - name: install packages and run on simulator
        run: |
          yarn
          yarn prepare
                  
      - name: Putting on npm repo
        run: |
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          
