name: PR - test

on:
  pull_request:
    types:
      - opened
    branches:    
      - 'main'
jobs:
  PR_test:
    runs-on: macos-12
        
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        
      - name: check enviroment
        run: |
          echo $ANDROID_NDK_HOME
          echo $ANDROID_SDK_ROOT
          
      - name: check File content
        run: |
          cat sameer.txt
      


      
      
          

          
