name: PR - Close

on:
  pull_request:
    #types:
    #  - closed
    branches:
      - 'main'

jobs:
  new_version:
    #if: github.event.pull_request.merged == true
    if: github.event.pull_request.merged == false
    runs-on: macos-12
    steps:    
    - name: 'Automated Version Bump'
      uses: 'phips28/gh-action-bump-version@master'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          minor-wording:  'add,Adds,new'
          major-wording:  'MAJOR,cut-major'
          patch-wording:  'patch,fixes'     # Providing patch-wording will override commits
                                      # defaulting to a patch bump.
          rc-wording:     'RELEASE,alpha'
