name: PR - test

on:
  pull_request:
    branches:    
      - 'main'
jobs:
  pr_test:
    runs-on: macos-12
        
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
         node-version: 16.x
         registry-url: https://registry.npmjs.org/
         
      - name: Update swift version
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.6.1"
         
      - name: Build it 
        run: |
          yarn
          cd example
          yarn
          
      - name: run ios tests
        run: |
          cd ios
          pod install
          yarn example run ios
          
      - name: run android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          profile: pixel_2
          emulator-build: 6110076
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: yarn example run android
      


      
      
          

          
